services:
    - type: web
      name: feel-app
      env: python
      buildCommand: "./render_build.sh"
      startCommand: "gunicorn app:app --chdir ./src/"
      envVars:
          - key: FLASK_APP
            value: src/app.py
          - key: FLASK_DEBUG
            value: 0
