"""empty message

Revision ID: 2e3e1dd552af
Revises: e602ab231d8c
Create Date: 2026-04-21 01:42:52.993950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e3e1dd552af'
down_revision = 'e602ab231d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_type', sa.String(length=10), nullable=False))
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
        batch_op.alter_column('receiver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('sender_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('sender_type')

    # ### end Alembic commands ###
