"""empty message

Revision ID: 422fbfba3b87
Revises: affd22559e52
Create Date: 2026-03-26 19:50:58.627316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '422fbfba3b87'
down_revision = 'affd22559e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('sign_up_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('sign_up_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('coaches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('sign_up_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('emotions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('emoji', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admint_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admint_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admint_id'], ['admints.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reaction_admint_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('admint_post_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['admint_post_id'], ['admint_posts.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'admint_post_id', name='unique_client_post_reaction')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_admint_post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('admint_post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('emotion_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admint_post_id'], ['admint_post.id'], name=op.f('reaction_admint_post_admint_post_id_fkey')),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name=op.f('reaction_admint_post_client_id_fkey')),
    sa.ForeignKeyConstraint(['emotion_id'], ['emotion.id'], name=op.f('reaction_admint_post_emotion_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_admint_post_pkey'))
    )
    op.create_table('emotion',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('emoji', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('emotion_pkey')),
    sa.UniqueConstraint('name', name=op.f('emotion_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('admint',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('admint_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sign_up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='admint_pkey'),
    sa.UniqueConstraint('email', name='admint_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('admint_post',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admint_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admint_id'], ['admint.id'], name=op.f('admint_post_admint_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('admint_post_pkey'))
    )
    op.create_table('coach',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sign_up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('coach_pkey')),
    sa.UniqueConstraint('email', name=op.f('coach_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('client',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sign_up_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('client_pkey')),
    sa.UniqueConstraint('email', name=op.f('client_email_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('reaction_admint_posts')
    op.drop_table('admint_posts')
    op.drop_table('emotions')
    op.drop_table('coaches')
    op.drop_table('clients')
    op.drop_table('admints')
    # ### end Alembic commands ###
