"""empty message

Revision ID: 555a5c8dbddf
Revises: 3a22ccb60c54
Create Date: 2026-04-09 21:04:34.312109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555a5c8dbddf'
down_revision = '3a22ccb60c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('emotion_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.alter_column('emotion_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
