"""empty message

Revision ID: 75927f850f04
Revises: b82da86eeab6
Create Date: 2026-03-26 17:36:11.366658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75927f850f04'
down_revision = 'b82da86eeab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_admint_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('admint_post_id', sa.Integer(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('reaction', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['admint_post_id'], ['admint_post.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction_admint_post')
    # ### end Alembic commands ###
