"""empty message

Revision ID: 80ed14bdede9
Revises: 91e80fcf051d
Create Date: 2026-04-03 22:43:53.651652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80ed14bdede9'
down_revision = '91e80fcf051d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reaction_entries')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reaction_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('entries_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('reaction', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('reaction_entries_client_id_fkey')),
    sa.ForeignKeyConstraint(['entries_id'], ['entries.id'], name=op.f('reaction_entries_entries_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('reaction_entries_pkey'))
    )
    # ### end Alembic commands ###
