"""empty message

Revision ID: 901f40e1fcb9
Revises: 8a41588c4673
Create Date: 2026-03-27 22:11:26.285025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '901f40e1fcb9'
down_revision = '8a41588c4673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_post')
    # ### end Alembic commands ###
