"""empty message

Revision ID: affd22559e52
Revises: 75927f850f04
Create Date: 2026-03-26 18:32:34.551202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affd22559e52'
down_revision = '75927f850f04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction_admint_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotion_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'emotion', ['emotion_id'], ['id'])
        batch_op.drop_column('emoji')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reaction_admint_post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emoji', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('emotion_id')

    # ### end Alembic commands ###
