"""empty message

Revision ID: b82da86eeab6
Revises: 05c5016493b5
Create Date: 2026-03-22 17:18:05.930103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b82da86eeab6'
down_revision = '05c5016493b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admint_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admint_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('img_url', sa.String(length=500), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admint_id'], ['admint.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admint_post')
    # ### end Alembic commands ###
